#!/bin/bash

mkdir -p $1

rm -f /tmp/halfs.log

#cabal build

echo "Mounting..."
dist/build/halfs/halfs -m $1 
#df -a
#ls -lrt $1
#echo foo > $1/bar

echo "Mounted."

echo "Waiting..."
sleep 1
echo "Woke up."

echo "Unmounting..."
umount $1
echo "Unmounted."

echo "*** Log begin ***"
if [ -e /tmp/halfs.log ] 
  then
    cat /tmp/halfs.log 
fi
echo "*** Log end ***"

echo "Done."

